openapi: 3.0.0
info:
  title: User registration API
  description: User registration API - Coding practice
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a user
      description: Create a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  admin:
                    type: boolean
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        "400":
          description: Email address is already in the database.
  /users/{user_id}/admin:
    patch:
      summary: Make user admin
      description: Make user admin
      parameters:
        - name: user_id
          in: path
          description: User ID
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  admin:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        "404":
          description: User does not exist.
  /users/{user_id}:
    get:
      summary: Show user profile
      description: Show user profile
      parameters:
        - name: user_id
          in: path
          description: User ID
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  admin:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        "404":
          description: User does not exist.
  /users/:
    get:
      summary: Show user profile
      description: Show user profile
      parameters:
        - name: user_id
          in: header
          description: User ID
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    admin:
                      type: string
                    email:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
        "400":
          description: This action requires admin privileges.
