openapi: 3.0.0
info:
  title: User registration API
  description: User registration API - Coding practice
  version: 1.0.0
paths:
  "/users":
    post:
      tags:
        - Category
      summary: Create a user
      description: Create a user
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  admin:
                    type: boolean
                  email:
                    type: string
                  created_at:
                    type: Date
                  updated_at:
                    type: Date
        "400":
          description: Email address is already in the database.
